#!/usr/bin/env python3
"""
Fetch https://slaythespire-2.com/card-tier and write data/tier_lists/slaythespire2_com_cards.json
(same shape as mobalytics_cards.json).

Use when the wiki page changes tiers. Run from repo root:

    python scripts/scrape_sts2_wiki_tiers.py

Requires network.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from urllib.request import Request, urlopen

URL = "https://slaythespire-2.com/card-tier"
OUT = Path(__file__).resolve().parent.parent / "data" / "tier_lists" / "slaythespire2_com_cards.json"

TIER_ROW = re.compile(
    r"bg-(?:red|orange|yellow|green|rose)-500[^>]*>\s*<span>([SABCDF])</span>|"
    r"bg-gray-(?:500|800)[^>]*>\s*<span>([SABCDF])</span>",
    re.IGNORECASE,
)
HREF_CARD = re.compile(r'href="/cards/([^"]+)"')

CHAR_MARKERS: list[tuple[str, str]] = [
    ("Ironclad", "Ironclad Card"),
    ("Silent", "Silent Card"),
    ("Defect", "Defect Card"),
    ("Regent", "Regent Card"),
    ("Necrobinder", "Necrobinder Card"),
]

_SLUG_SPECIAL: dict[str, str] = {
    "pacts-end": "Pact's End",
    "times-up": "Time's Up",
    "banshees-cry": "Banshee's Cry",
    "monarchs-gaze": "Monarch's Gaze",
    "strike-necrobinder": "Strike",
    "multi-cast": "Multi-Cast",
    "all-for-one": "All for One",
    "charge": "CHARGE!!",
    "guards": "GUARDS!!!",
    "begone": "BEGONE!",
    "expect-a-fight": "Expect a Fight",
    "ftl": "FTL",
    "null": "Null",
}


def slug_to_name(slug: str) -> str:
    if slug in _SLUG_SPECIAL:
        return _SLUG_SPECIAL[slug]
    parts = slug.split("-")
    return " ".join(p.capitalize() for p in parts)


def _slice_character_sections(html: str) -> dict[str, str]:
    positions: list[tuple[int, str]] = []
    for char, needle in CHAR_MARKERS:
        i = html.find(needle)
        if i >= 0:
            positions.append((i, char))
    positions.sort(key=lambda x: x[0])
    out: dict[str, str] = {}
    for j, (start, char) in enumerate(positions):
        end = positions[j + 1][0] if j + 1 < len(positions) else len(html)
        out[char] = html[start:end]
    return out


def parse_character_html(segment: str) -> dict[str, list[str]]:
    tiers: dict[str, list[str]] = {}
    matches = list(TIER_ROW.finditer(segment))
    for i, m in enumerate(matches):
        tier = (m.group(1) or m.group(2) or "").upper()
        if tier not in "SABCDF":
            continue
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(segment)
        chunk = segment[start:end]
        for sm in HREF_CARD.finditer(chunk):
            slug = sm.group(1).strip().lower()
            if not slug or slug.startswith("http"):
                continue
            name = slug_to_name(slug)
            bucket = tiers.setdefault(tier, [])
            if name not in bucket:
                bucket.append(name)
    return tiers


def main() -> int:
    req = Request(URL, headers={"User-Agent": "Mozilla/5.0 BoberInSpire-tier-scraper/1.0"})
    with urlopen(req, timeout=90) as resp:
        html = resp.read().decode("utf-8", errors="replace")

    if "/cards/" not in html:
        print("No card links in response", file=sys.stderr)
        return 1

    sections = _slice_character_sections(html)
    if not sections:
        print("Could not find character sections", file=sys.stderr)
        return 1

    characters: dict[str, dict[str, list[str]]] = {}
    for char, seg in sections.items():
        parsed = parse_character_html(seg)
        if parsed:
            characters[char] = parsed

    payload = {
        "source": URL,
        "note": "Generated by scripts/scrape_sts2_wiki_tiers.py from slaythespire-2.com; re-run to refresh.",
        "characters": characters,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    total = sum(len(v) for t in characters.values() for v in t.values())
    print(f"Wrote {OUT} ({len(characters)} chars, {total} card placements)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
